{
	panic(funcname + " failed: " + err.Error())
}